### ISSUE TITLE
vulp hands are switched

### ISSUE THREAD

**Issue by deltanedas** [Goob-Station/Goob-Station#822] opened 2024-11-05 15:57 UTC
## Description
left is right, right is left

![03:56:09](https://github.com/user-attachments/assets/f6219aed-212d-4c75-826f-02083e9839a2)

may be an event issue

**Comment by Piras314** [comment] 2024-11-05 22:12
was able to reproduce this, no idea why it's happening though

**Comment by Piras314** [comment] 2024-11-05 22:32
HAHAHA I FIXED IT OH MY GOD THAT'S SO FUNNY AND DUMB

**Comment by Piras314** [comment] 2024-11-05 22:34
applies to felinids and harpies, fixing it for them as well

**Comment by Piras314** [comment] 2024-11-05 22:36
Fixed by #824

**Comment by AstroDogeDX** [comment] 2024-11-06 03:14
oh lmao I was about to make a PR to fix this; the reason why it's broken is SO DUMB.

**Comment by deltanedas** [comment] 2024-11-06 09:51
> Fixed by #824

pro you write `fixed #824` in the pr for it to autoclose

**Comment by Piras314** [comment] 2024-11-06 14:02
Fixed #824

**Closed** 2024-11-06 23:35 UTC
Labels: bug
